/**
 * SongDisplay.jsx — v2.1
 * Final song with:
 * - CRT-glow archetype name (Bebas Neue + green text-shadow + glitch on hover)
 * - Temporal conflict score badge (from PIRE layer)
 * - Section cards with left accent border matching section color
 * - Regen button with rotation animation
 * - Staggered section entrance
 */
import { useState } from 'react'
import GlitchText from '../components/GlitchText'
import HookBookPanel from '../components/HookBookPanel'
import styles from './SongDisplay.module.css'

const SECTION_COLORS = {
  verse:              'var(--green-dim)',
  hook:               'var(--magenta)',
  'pre-hook':         'var(--warning)',
  bridge:             'var(--green)',
  intro:              'var(--grey-mid)',
  outro:              'var(--text-dim)',
  'spoken-word':      'var(--magenta-dim)',
  'call-and-response':'var(--green)',
}

export default function SongDisplay({ song, analysis, onRestart }) {
  const [copied,      setCopied]       = useState(false)
  const [view,        setView]         = useState('sections')
  const [sections,    setSections]     = useState(song.sections)
  const [regenerating,setRegenerating] = useState({})
  const [seedMap,     setSeedMap]      = useState({})
  const [hookOpen,    setHookOpen]    = useState(false)

  // ── Per-section regenerate ────────────────────────────────────────────────
  async function regenerateSection(idx) {
    const apiKey   = localStorage.getItem('sci_api_key')
    const provider = localStorage.getItem('sci_provider') || 'claude'
    if (!apiKey) { alert('No API key — re-run from the cockpit.'); return }

    const newSeed = (seedMap[idx] || 0) + 1
    setSeedMap(prev => ({ ...prev, [idx]: newSeed }))
    setRegenerating(prev => ({ ...prev, [idx]: true }))
    try {
      const section = sections[idx]
      const res = await fetch('http://localhost:3001/api/section', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          section:          { ...section, lyrics: undefined },
          persona:          analysis?.persona,
          message:          analysis?.message,
          style:            analysis?.style,
          previousSections: sections.slice(0, idx).map(s => s.lyrics),
          apiKey, provider, seed: newSeed,
        }),
      })
      const data = await res.json()
      if (data.success && data.section) {
        setSections(prev => {
          const next = [...prev]
          next[idx] = { ...next[idx], lyrics: data.section.lyrics }
          return next
        })
      }
    } catch (err) {
      console.error('Regen error:', err)
    } finally {
      setRegenerating(prev => ({ ...prev, [idx]: false }))
    }
  }

  function copyToClipboard() {
    const text = sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n')
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true); setTimeout(() => setCopied(false), 2000)
    })
  }

  function downloadTxt() {
    const conflictInfo = analysis?.message?.temporalProfile
      ? `\nConflict Score: ${analysis.message.temporalProfile.conflictScore} | ${analysis.message.temporalProfile.logicalRelation?.relation}`
      : ''
    const meta = [
      `SONG — Generated by SCI (Structured Creative Intelligence) v2.1`,
      `Archetype:    ${song.metadata.archetype}`,
      `Core Message: ${song.metadata.coreMessage}`,
      `Language:     ${song.metadata.language}`,
      `Structure:    ${song.metadata.structure}`,
      conflictInfo,
      `Generated:    ${new Date().toLocaleString()}`,
      '', '═'.repeat(52), '',
      sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n'),
    ].join('\n')

    const blob = new Blob([meta], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = `sci-song-${Date.now()}.txt`; a.click()
    URL.revokeObjectURL(url)
  }

  async function saveSession() {
    try {
      await fetch('http://localhost:3001/api/save', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...analysis, sections, metadata: song.metadata }),
      })
      alert('Session saved to ~/.sci-sessions/')
    } catch { alert('Save failed — backend running?') }
  }

  // Temporal/PIRE data
  const tp = analysis?.message?.temporalProfile
  const conflictScore  = tp?.conflictScore
  const logicalRel     = tp?.logicalRelation?.relation
  const conflictLabel  = conflictScore >= 0.7 ? 'EXTREME' : conflictScore >= 0.4 ? 'HIGH' : 'MODERATE'
  const relColor = {
    CONTRADICTION: 'var(--magenta)',
    CONTRARY:      'var(--warning)',
    SUBCONTRARY:   'var(--green)',
    NEUTRAL:       'var(--text-muted)',
  }[logicalRel] || 'var(--text-muted)'

  return (
    <div className={styles.page}>
      <div className={styles.content}>

        {/* ── Hero ─────────────────────────────────────────────────────────── */}
        <div className={styles.hero}>
          <div className={styles.heroBadge}>◈ SCI v2 — EXCAVATED</div>
          <GlitchText
            text={song.metadata.archetype}
            as="h1"
            className={styles.archetype}
            loop
          />
          <p className={styles.coreMsg}>"{song.metadata.coreMessage}"</p>

          <div className={styles.metaRow}>
            <MetaTag v={song.metadata.language} />
            <MetaTag v={song.metadata.structure?.replace(/_/g,' ')} />
            <MetaTag v={`${sections.length} sections`} />
          </div>

          {/* PIRE badge */}
          {logicalRel && (
            <div className={styles.pireBadge}>
              <span className={styles.pireRel} style={{ color: relColor, borderColor: relColor }}>
                {logicalRel}
              </span>
              <span className={styles.pireScore}>
                Conflict {Math.round(conflictScore * 100)}/100 — {conflictLabel}
              </span>
            </div>
          )}
        </div>

        {/* ── View toggle ──────────────────────────────────────────────────── */}
        <div className={styles.viewToggle}>
          <button
            className={[styles.viewBtn, view === 'sections' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('sections')}
          >Structured</button>
          <button
            className={[styles.viewBtn, view === 'plain' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('plain')}
          >Plain Text</button>
        </div>

        {/* ── Song body ────────────────────────────────────────────────────── */}
        <div className={styles.songBody}>
          {view === 'sections' ? (
            sections.map((section, i) => {
              const color = SECTION_COLORS[section.type] || 'var(--green)'
              return (
                <div
                  key={i}
                  className={styles.sectionCard}
                  style={{ '--c': color, animationDelay: `${i * 0.07}s` }}
                >
                  <div className={styles.sectionAccent} />
                  <div className={styles.sectionMeta}>
                    <span className={styles.sectionType}>{section.type.toUpperCase()}</span>
                    <span className={styles.sectionGoal}>{section.goal?.replace(/_/g,' ')}</span>
                    <button
                      className={[styles.regenBtn, regenerating[i] ? styles.regenSpinning : ''].join(' ')}
                      onClick={() => regenerateSection(i)}
                      disabled={!!regenerating[i]}
                      title={`Regenerate (variation ${(seedMap[i]||0)+1})`}
                    >
                      ↻
                    </button>
                  </div>
                  <pre className={styles.lyrics}>{section.lyrics}</pre>
                </div>
              )
            })
          ) : (
            <pre className={styles.plainLyrics}>
              {sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n')}
            </pre>
          )}
        </div>

        {/* ── Actions ──────────────────────────────────────────────────────── */}
        <div className={styles.actions}>
          <button className={styles.copyBtn}     onClick={copyToClipboard}>
            {copied ? '✓ Copied' : '⌘ Copy'}
          </button>
          <button className={styles.downloadBtn} onClick={downloadTxt}>↓ .txt</button>
          <button className={styles.saveBtn}     onClick={saveSession}>⬡ Save</button>
          <button className={styles.restartBtn}  onClick={onRestart}>↺ New Song</button>
        </div>

        <div className={styles.footer}>
          <span className={styles.footerLine} />
          <p className={styles.footerNote}>
            SCI v2 · Identity → Persona → Message → Structure → Song
          </p>
          <span className={styles.footerLine} />
        </div>
      </div>

      {/* ── HookBook FAB ──────────────────────────────────────────────────── */}
      <button
        className={styles.hookFab}
        onClick={() => setHookOpen(true)}
        title="Open HookBook — lyric analysis"
      >
        ⊕ HOOKBOOK
      </button>

      {/* ── HookBook Drawer ───────────────────────────────────────────────── */}
      <HookBookPanel
        open={hookOpen}
        onClose={() => setHookOpen(false)}
        sections={sections}
      />
    </div>
  )
}

function MetaTag({ v }) {
  return <span className={styles.metaTag}>{v}</span>
}
