/**
 * SongDisplay.jsx — v2
 * Final song display with per-section regenerate (↺) button.
 * Theme: green + magenta + B&W.
 *
 * @deprecated Questionnaire.jsx and PersonaReview.jsx are kept in /pages
 * but are no longer routed to — Cockpit.jsx replaces them.
 */
import { useState } from 'react'
import styles from './SongDisplay.module.css'

const SECTION_COLORS = {
  verse:             'var(--green-dim)',
  hook:              'var(--magenta)',
  'pre-hook':        'var(--warning)',
  bridge:            'var(--green)',
  intro:             'var(--grey-mid)',
  outro:             'var(--text-dim)',
  'spoken-word':     'var(--magenta-dim)',
  'call-and-response':'var(--green)',
}

export default function SongDisplay({ song, analysis, onRestart }) {
  const [copied,      setCopied]      = useState(false)
  const [view,        setView]        = useState('sections')
  const [sections,    setSections]    = useState(song.sections)
  const [regenerating,setRegenerating]= useState({}) // { [index]: true }
  const [seedMap,     setSeedMap]     = useState({})  // { [index]: seedCount }

  // ── Per-section regenerate ──────────────────────────────────────────────────
  async function regenerateSection(sectionIndex) {
    const apiKey  = localStorage.getItem('sci_api_key')
    const provider= localStorage.getItem('sci_provider') || 'claude'
    if (!apiKey) { alert('No API key stored — re-run from the cockpit.'); return }

    const newSeed = (seedMap[sectionIndex] || 0) + 1
    setSeedMap(prev => ({ ...prev, [sectionIndex]: newSeed }))
    setRegenerating(prev => ({ ...prev, [sectionIndex]: true }))

    try {
      const section = sections[sectionIndex]
      const res = await fetch('http://localhost:3001/api/section', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          section:          { ...section, lyrics: undefined },
          persona:          analysis?.persona,
          message:          analysis?.message,
          style:            analysis?.style,
          previousSections: sections.slice(0, sectionIndex).map(s => s.lyrics),
          apiKey,
          provider,
          seed: newSeed,
        }),
      })
      const data = await res.json()
      if (data.success && data.section) {
        setSections(prev => {
          const updated = [...prev]
          updated[sectionIndex] = { ...updated[sectionIndex], lyrics: data.section.lyrics }
          return updated
        })
      }
    } catch (err) {
      console.error('Regenerate error:', err)
    } finally {
      setRegenerating(prev => ({ ...prev, [sectionIndex]: false }))
    }
  }

  // ── Clipboard / download ────────────────────────────────────────────────────
  function copyToClipboard() {
    const text = sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n')
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function downloadTxt() {
    const meta = [
      `SONG — Generated by SCI (Structured Creative Intelligence) v2`,
      `Archetype:    ${song.metadata.archetype}`,
      `Core Message: ${song.metadata.coreMessage}`,
      `Language:     ${song.metadata.language}`,
      `Structure:    ${song.metadata.structure}`,
      `Generated:    ${new Date().toLocaleString()}`,
      '', '═'.repeat(50), '',
      sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n'),
    ].join('\n')

    const blob = new Blob([meta], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = `sci-song-${Date.now()}.txt`; a.click()
    URL.revokeObjectURL(url)
  }

  // ── Save session ────────────────────────────────────────────────────────────
  async function saveSession() {
    try {
      await fetch('http://localhost:3001/api/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...analysis,
          sections,
          metadata: song.metadata,
        }),
      })
      alert('Session saved to ~/.sci-sessions/')
    } catch { alert('Save failed — is the backend running?') }
  }

  return (
    <div className={styles.page}>
      <div className={styles.content}>

        {/* Header */}
        <div className={styles.hero}>
          <div className={styles.heroBadge}>◈ SCI v2</div>
          <h2 className={styles.archetype}>{song.metadata.archetype}</h2>
          <p className={styles.coreMsg}>"{song.metadata.coreMessage}"</p>
          <div className={styles.metaRow}>
            <span className={styles.metaTag}>{song.metadata.language}</span>
            <span className={styles.metaTag}>{song.metadata.structure?.replace(/_/g,' ')}</span>
            <span className={styles.metaTag}>{sections.length} sections</span>
          </div>
        </div>

        {/* View toggle */}
        <div className={styles.viewToggle}>
          <button
            className={[styles.viewBtn, view==='sections' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('sections')}
          >Structured View</button>
          <button
            className={[styles.viewBtn, view==='plain' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('plain')}
          >Plain Text</button>
        </div>

        {/* Song body */}
        <div className={styles.songBody}>
          {view === 'sections' ? (
            sections.map((section, i) => (
              <div key={i} className={styles.sectionCard}>
                <div className={styles.sectionMeta}>
                  <span
                    className={styles.sectionType}
                    style={{ '--c': SECTION_COLORS[section.type] || 'var(--green)' }}
                  >
                    {section.type.toUpperCase()}
                  </span>
                  <span className={styles.sectionGoal}>
                    {section.goal?.replace(/_/g,' ')}
                  </span>
                  {/* ↺ Per-section regenerate button (v2) */}
                  <button
                    className={styles.regenBtn}
                    onClick={() => regenerateSection(i)}
                    disabled={!!regenerating[i]}
                    title={`Regenerate this ${section.type} (variation ${(seedMap[i]||0)+1})`}
                  >
                    {regenerating[i] ? '…' : '↺'}
                  </button>
                </div>
                <pre className={styles.lyrics}>{section.lyrics}</pre>
              </div>
            ))
          ) : (
            <pre className={styles.plainLyrics}>
              {sections.map(s => `[${s.type.toUpperCase()}]\n${s.lyrics}`).join('\n\n')}
            </pre>
          )}
        </div>

        {/* Actions */}
        <div className={styles.actions}>
          <button className={styles.copyBtn}     onClick={copyToClipboard}>
            {copied ? '✓ Copied!' : '⎘ Copy Lyrics'}
          </button>
          <button className={styles.downloadBtn} onClick={downloadTxt}>
            ↓ Download .txt
          </button>
          <button className={styles.saveBtn}     onClick={saveSession}>
            ⬡ Save Session
          </button>
          <button className={styles.restartBtn}  onClick={onRestart}>
            ↺ Write Another Song
          </button>
        </div>

        <div className={styles.footer}>
          <p className={styles.footerNote}>
            Built with <strong>SCI v2</strong> — Structured Creative Intelligence.
            Identity → Persona → Message → Structure → Song.
          </p>
        </div>
      </div>
    </div>
  )
}
